## Lab 2

# Title
## Subtitle
### Subtitle 2
#### Subtitle 3
##### Header
###### Highlight

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from typing_extensions import overload

penguins=sns.load_dataset("penguins")

## Explorare date

In [2]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [3]:
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [4]:
penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [5]:
penguins[penguins.columns[2:4]]

     bill_length_mm  bill_depth_mm
0              39.1           18.7
1              39.5           17.4
2              40.3           18.0
3               NaN            NaN
4              36.7           19.3
..              ...            ...
339             NaN            NaN
340            46.8           14.3
341            50.4           15.7
342            45.2           14.8
343            49.9           16.1

[344 rows x 2 columns]

In [6]:
penguins.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

## Curatare dateset

In [7]:
penguins.isna().sum() #isna=isnull

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [8]:
import numpy as np
penguins[penguins["sex"]== "Male"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
...,...,...,...,...,...,...,...
333,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,Male
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,Male
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,Male
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [9]:
penguins[penguins["sex"]=="Female"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female
...,...,...,...,...,...,...,...
332,Gentoo,Biscoe,43.5,15.2,213.0,4650.0,Female
334,Gentoo,Biscoe,46.2,14.1,217.0,4375.0,Female
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female

In [10]:
penguins.species.unique()

<StringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str

In [11]:
penguins[penguins["species"]=="Adelie"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,Female
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female
149,Adelie,Dream,37.8,18.1,193.0,3750.0,Male
150,Adelie,Dream,36.0,17.1,187.0,3700.0,Female
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male

In [12]:
penguins[penguins["species"].isin(['Adelie ','Chinstrap'])]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
152,Chinstrap,Dream,46.5,17.9,192.0,3500.0,Female
153,Chinstrap,Dream,50.0,19.5,196.0,3900.0,Male
154,Chinstrap,Dream,51.3,19.2,193.0,3650.0,Male
155,Chinstrap,Dream,45.4,18.7,188.0,3525.0,Female
156,Chinstrap,Dream,52.7,19.8,197.0,3725.0,Male
...,...,...,...,...,...,...,...
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,Male
216,Chinstrap,Dream,43.5,18.1,202.0,3400.0,Female
217,Chinstrap,Dream,49.6,18.2,193.0,3775.0,Male
218,Chinstrap,Dream,50.8,19.0,210.0,4100.0,Male
219,Chinstrap,Dream,50.2,18.7,198.0,3775.0,Female

In [13]:
#filtrare toti pinguini din specia adelie care se afla pe insula Biscoe
penguins[penguins["species"].isin(['Adelie']) & penguins["island"].isin(['Biscoe'])]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,Female
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,Male
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,Female
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,Male
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,Male
25,Adelie,Biscoe,35.3,18.9,187.0,3800.0,Female
26,Adelie,Biscoe,40.6,18.6,183.0,3550.0,Male
27,Adelie,Biscoe,40.5,17.9,187.0,3200.0,Female
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,Female
29,Adelie,Biscoe,40.5,18.9,180.0,3950.0,Male
50,Adelie,Biscoe,39.6,17.7,186.0,3500.0,Female
51,Adelie,Biscoe,40.1,18.9,188.0,4300.0,Male
52,Adelie,Biscoe,35.0,17.9,190.0,3450.0,Female
53,Adelie,Biscoe,42.0,19.5,200.0,4050.0,Male
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,Female
55,Adelie,Biscoe,41.4,18.6,191.0,3700.0,Male
56,Adelie,Biscoe,39.0,17.5,186.0,3550.0,Female
57,Adelie,Biscoe,40.6,18.8,193.0,3800.0,Male
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,Female
59,Adelie,Biscoe,37.6,19.1,194.0,3750.0,Male
60,Adelie,Biscoe,35.7,16.9,185.0,3150.0,Female
61,Adelie,Biscoe,41.3,21.1,195.0,4400.0,Male
62,Adelie,Biscoe,37.6,17.0,185.0,3600.0,Female
63,Adelie,Biscoe,41.1,18.2,192.0,4050.0,Male
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,Female
65,Adelie,Biscoe,41.6,18.0,192.0,3950.0,Male
66,Adelie,Biscoe,35.5,16.2,195.0,3350.0,Female
67,Adelie,Biscoe,41.1,19.1,188.0,4100.0,Male
100,Adelie,Biscoe,35.0,17.9,192.0,3725.0,Female
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,Male
102,Adelie,Biscoe,37.7,16.0,183.0,3075.0,Female
103,Adelie,Biscoe,37.8,20.0,190.0,4250.0,Male
104,Adelie,Biscoe,37.9,18.6,193.0,2925.0,Female
105,Adelie,Biscoe,39.7,18.9,184.0,3550.0,Male
106,Adelie,Biscoe,38.6,17.2,199.0,3750.0,Female
107,Adelie,Biscoe,38.2,20.0,190.0,3900.0,Male
108,Adelie,Biscoe,38.1,17.0,181.0,3175.0,Female
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,Male
110,Adelie,Biscoe,38.1,16.5,198.0,3825.0,Female
111,Adelie,Biscoe,45.6,20.3,191.0,4600.0,Male
112,Adelie,Biscoe,39.7,17.7,193.0,3200.0,Female
113,Adelie,Biscoe,42.2,19.5,197.0,4275.0,Male
114,Adelie,Biscoe,39.6,20.7,191.0,3900.0,Female
115,Adelie,Biscoe,42.7,18.3,196.0,4075.0,Male

In [14]:
penguins["bill_area"]=penguins["bill_length_mm"] * penguins["bill_depth_mm"]

In [15]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_area
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,731.17
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,687.30
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,725.40
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,708.31

In [16]:
penguins_no_null=penguins.dropna()
penguins_no_null["bill_area"]=penguins_no_null["bill_length_mm"].dot(penguins_no_null["bill_depth_mm"]) #.dot inmultire matriciala
penguins_no_null.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_area
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,250640.99
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,250640.99
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,250640.99
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,250640.99
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,250640.99

In [17]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_area
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,731.17
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,687.30
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,725.40
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,708.31

In [29]:
penguins_numerical=penguins[penguins.columns[2:7]].groupby("sex")

In [30]:
penguins_numerical.aggregate("mean") #agregare dupa medie

        bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
sex
Female       42.096970      16.425455         197.363636  3862.272727
Male         45.854762      17.891071         204.505952  4545.684524

In [31]:
male_penguins=penguins_numerical.get_group("Male")
female_penguins=penguins_numerical.get_group("Female")

In [32]:
male_penguins.head()

    bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g   sex
0             39.1           18.7              181.0       3750.0  Male
5             39.3           20.6              190.0       3650.0  Male
7             39.2           19.6              195.0       4675.0  Male
13            38.6           21.2              191.0       3800.0  Male
14            34.6           21.1              198.0       4400.0  Male

In [41]:
numeric_male_pengiun=male_penguins.select_dtypes(include="number") #sau exclude="str"
numeric_male_pengiun.fillna(numeric_male_pengiun.mean())

numeric_female_pengiun=female_penguins.select_dtypes(include="number") #sau exclude="str"
numeric_female_pengiun.fillna(numeric_female_pengiun.mean())

     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
4              36.7           19.3              193.0       3450.0
6              38.9           17.8              181.0       3625.0
12             41.1           17.6              182.0       3200.0
..              ...            ...                ...          ...
332            43.5           15.2              213.0       4650.0
334            46.2           14.1              217.0       4375.0
338            47.2           13.7              214.0       4925.0
340            46.8           14.3              215.0       4850.0
342            45.2           14.8              212.0       5200.0

[165 rows x 4 columns]

In [42]:
numeric_female_pengiun.head()

    bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
1             39.5           17.4              186.0       3800.0
2             40.3           18.0              195.0       3250.0
4             36.7           19.3              193.0       3450.0
6             38.9           17.8              181.0       3625.0
12            41.1           17.6              182.0       3200.0

In [43]:
numeric_male_pengiun.head()

    bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0             39.1           18.7              181.0       3750.0
5             39.3           20.6              190.0       3650.0
7             39.2           19.6              195.0       4675.0
13            38.6           21.2              191.0       3800.0
14            34.6           21.1              198.0       4400.0

In [44]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_area
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,731.17
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,687.30
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,725.40
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,708.31

In [46]:
penguins=penguins[["species","island","sex"]]
clean_peanguins=penguins.join(numeric_male_pengiun)
clean_peanguins=clean_peanguins.join((numeric_female_pengiun))

ValueError: columns overlap but no suffix specified: Index(['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g'], dtype='str')